name: CI/CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install

      # Diagnóstico
      - run: ls -l ./node_modules/.bin/react-scripts

      # Forzar permiso (si necesario)
      - run: chmod +x ./node_modules/.bin/react-scripts

      # Ejecutar test y build usando npx para evitar problemas de path o permisos
      - run: npx react-scripts test --watchAll=false
      - run: npx react-scripts build

      - uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./build
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
